name = "badger2040_bsp"
description = "Pimoroni Badger 2040 BSP"
version = "0.1.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

[[depends-on]]
rp2040_hal = "^2.0.0-dev"
adl_middleware = "~0.1.1"

[configuration.values]
rp2040_hal.Flash_Chip = "w25qxx"

[[pins]]
rp2040_hal = { url="https://github.com/JeremyGrosser/rp2040_hal.git" }
