name = "badger_demo"
description = "Shiny new project"
version = "0.1.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

executables = ["badger_demo"]

[[depends-on]]
badger2040_bsp = "~0.1.0"
tiny_text = "^1.1.0"

[[pins]]
badger2040_bsp = { path='../' }
tiny_text = { url='https://github.com/JeremyGrosser/tiny_text' }   # Added by alr

[gpr-set-externals]
RP2040_HAL_BUILD_MODE = "debug"
