name = "badger_demo"
description = "Shiny new project"
version = "0.1.0"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]

executables = ["badger_demo"]
[[depends-on]]
badger2040_bsp = "~0.1.0"

[[pins]]
badger2040_bsp = { path='../../badger2040_bsp' }

[gpr-set-externals]
RP2040_HAL_BUILD_MODE = "debug"
[[depends-on]]  # Added by alr
tiny_text = "^1.1.0"  # Added by alr
[[pins]]  # Added by alr
tiny_text = { path='../../tiny_text' }   # Added by alr
